//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEC_Index_Test {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Common : global::System.Configuration.ApplicationSettingsBase {
        
        private static Common defaultInstance = ((Common)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Common())));
        
        public static Common Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoStart {
            get {
                return ((bool)(this["AutoStart"]));
            }
            set {
                this["AutoStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("server=172.1.10.88;database=sartas;user=sartas;pwd=sartas;port=3306;CharSet=utf8;" +
            " Convert Zero Datetime=True; Allow Zero Datetime=True;")]
        public string ConStr {
            get {
                return ((string)(this["ConStr"]));
            }
            set {
                this["ConStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\TOECProgramFiles\\DataImportExport\\")]
        public string Path_DataImportExport {
            get {
                return ((string)(this["Path_DataImportExport"]));
            }
            set {
                this["Path_DataImportExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\DATABACK\\TX_bak\\#E:\\DATABACK\\TX_ignore\\#E:\\DATABACK\\TX_disuse\\")]
        public string Path_SucceedXMLFolder {
            get {
                return ((string)(this["Path_SucceedXMLFolder"]));
            }
            set {
                this["Path_SucceedXMLFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\GQPics\\")]
        public string Path_Pic {
            get {
                return ((string)(this["Path_Pic"]));
            }
            set {
                this["Path_Pic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\lx\\")]
        public string Path_Video {
            get {
                return ((string)(this["Path_Video"]));
            }
            set {
                this["Path_Video"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\lx\\")]
        public string Path_Voice {
            get {
                return ((string)(this["Path_Voice"]));
            }
            set {
                this["Path_Voice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\DATABACK\\hotdata_bak\\")]
        public string Path_Hotwheel {
            get {
                return ((string)(this["Path_Hotwheel"]));
            }
            set {
                this["Path_Hotwheel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\ZXGQPics\\")]
        public string Path_ZXPic {
            get {
                return ((string)(this["Path_ZXPic"]));
            }
            set {
                this["Path_ZXPic"] = value;
            }
        }
    }
}
